### ISSUE TITLE
Problème de sécurité majeur!

### ISSUE THREAD

**Issue by 73VW** [HE-Arc/FreeGo#152]
@gaelchriste 
Comme discuté pendant la soutenance, **l'API n'est pas protégée**.

### Voilà quelques pistes
Si tu veux continuer d'utiliser Vue, j'ai trouvé ça qui m'a l'air pas mal: 

> https://bezkoder.com/django-vue-js-rest-framework/

J'ai pas testé et je connais pas Vue, donc c'est à prendre avec des pincettes. Sinon il doit y avoir bien d'autres tutoriels/exemples qui te permettent de sécuriser un peu plus tout ça.

Pour ma part, j'avais suivi le tutoriel [Pluralsight](https://www.pluralsight.com/) concernant Django et Angular que tu trouveras ici : 

> [Web Development with Django and AngularJS](https://app.pluralsight.com/library/courses/django-angularjs-web-development/table-of-contents)

Le résultat était plutôt pas mal mais attention, ce tuto date de 2016 donc ça a évolué depuis.

Sinon tu peux toujours rejoindre le gitter de la filière inf de la HE-Arc (regarde avec @grunenwald pour les modalités). Il y a passablement d'anciens élèves et profs qui sont dans l'industrie et qui pourraient t'aider.

Salutations.

**Comment by gaelchriste** [comment]
@73VW 
Je vais regarder ça, merci!
